name: mobile
description: Unified Investment Portfolio App
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
flutter:
  uses-material-design: true
